### ISSUE TITLE
Panic while flushing

### ISSUE THREAD

**Issue by cyriltovena** [grafana/phlare#640]
Found this one happening quite often in our cluster.

<img width="2168" alt="image" src="https://user-images.githubusercontent.com/1053421/233378998-3f444866-ae5a-40e7-bda6-728d48766af3.png">

```


2023-04-20 12:52:01.725	github.com/segmentio/parquet-go@v0.0.0-20221214174709-7a0ad59e0540/writer.go:206 +0x16d2023-04-20 12:52:01.725github.com/segmentio/parquet-go.(*Writer).ReadRowsFrom(0xc0005e8c00, {0x7febdf8bfea0, 0xc0562ac090})2023-04-20 12:52:01.725	github.com/segmentio/parquet-go@v0.0.0-20221214174709-7a0ad59e0540/row.go:331 +0x4362023-04-20 12:52:01.725github.com/segmentio/parquet-go.copyRows({0x49eb860, 0xc0000e29a0}, {0x7febdf8bfea0, 0xc0562ac090}, {0xc197656c00, 0x2a, 0x2a})2023-04-20 12:52:01.725	github.com/grafana/phlare/pkg/phlaredb/profile_store.go:459 +0xf42023-04-20 12:52:01.725github.com/grafana/phlare/pkg/phlaredb.(*seriesIDRowsRewriter).ReadRows(0xc0562ac090, {0xc197656c00?, 0xc0000e29a0?, 0x2a})2023-04-20 12:52:01.725	github.com/grafana/phlare/pkg/phlaredb/profiles.go:60 +0xa82023-04-20 12:52:01.725github.com/grafana/phlare/pkg/phlaredb.rowRangesWithSeriesIndex.getSeriesIndex({0xc19f6f0000?, 0xc197656c00?, 0x2a?}, 0x2a?)2023-04-20 12:52:01.725goroutine 368 [running]:2023-04-20 12:52:01.725 | 2023-04-20 12:52:01.725 | github.com/segmentio/parquet-go@v0.0.0-20221214174709-7a0ad59e0540/writer.go:206 +0x16d |   |   |   | 2023-04-20 12:52:01.725 | github.com/segmentio/parquet-go.(*Writer).ReadRowsFrom(0xc0005e8c00, {0x7febdf8bfea0, 0xc0562ac090}) |   |   |   | 2023-04-20 12:52:01.725 | github.com/segmentio/parquet-go@v0.0.0-20221214174709-7a0ad59e0540/row.go:331 +0x436 |   |   |   | 2023-04-20 12:52:01.725 | github.com/segmentio/parquet-go.copyRows({0x49eb860, 0xc0000e29a0}, {0x7febdf8bfea0, 0xc0562ac090}, {0xc197656c00, 0x2a, 0x2a}) |   |   |   | 2023-04-20 12:52:01.725 | github.com/grafana/phlare/pkg/phlaredb/profile_store.go:459 +0xf4 |   |   |   | 2023-04-20 12:52:01.725 | github.com/grafana/phlare/pkg/phlaredb.(*seriesIDRowsRewriter).ReadRows(0xc0562ac090, {0xc197656c00?, 0xc0000e29a0?, 0x2a}) |   |   |   | 2023-04-20 12:52:01.725 | github.com/grafana/phlare/pkg/phlaredb/profiles.go:60 +0xa8 |   |   |   | 2023-04-20 12:52:01.725 | github.com/grafana/phlare/pkg/phlaredb.rowRangesWithSeriesIndex.getSeriesIndex({0xc19f6f0000?, 0xc197656c00?, 0x2a?}, 0x2a?) |   |   |   | 2023-04-20 12:52:01.725 | goroutine 368 [running]: |   |   |   | 2023-04-20 12:52:01.725 |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
2023-04-20 12:52:01.725 | github.com/segmentio/parquet-go@v0.0.0-20221214174709-7a0ad59e0540/writer.go:206 +0x16d |  
  |   | 2023-04-20 12:52:01.725 | github.com/segmentio/parquet-go.(*Writer).ReadRowsFrom(0xc0005e8c00, {0x7febdf8bfea0, 0xc0562ac090}) |  
  |   | 2023-04-20 12:52:01.725 | github.com/segmentio/parquet-go@v0.0.0-20221214174709-7a0ad59e0540/row.go:331 +0x436 |  
  |   | 2023-04-20 12:52:01.725 | github.com/segmentio/parquet-go.copyRows({0x49eb860, 0xc0000e29a0}, {0x7febdf8bfea0, 0xc0562ac090}, {0xc197656c00, 0x2a, 0x2a}) |  
  |   | 2023-04-20 12:52:01.725 | github.com/grafana/phlare/pkg/phlaredb/profile_store.go:459 +0xf4 |  
  |   | 2023-04-20 12:52:01.725 | github.com/grafana/phlare/pkg/phlaredb.(*seriesIDRowsRewriter).ReadRows(0xc0562ac090, {0xc197656c00?, 0xc0000e29a0?, 0x2a}) |  
  |   | 2023-04-20 12:52:01.725 | github.com/grafana/phlare/pkg/phlaredb/profiles.go:60 +0xa8 |  
  |   | 2023-04-20 12:52:01.725 | github.com/grafana/phlare/pkg/phlaredb.rowRangesWithSeriesIndex.getSeriesIndex({0xc19f6f0000?, 0xc197656c00?, 0x2a?}, 0x2a?) |  
  |   | 2023-04-20 12:52:01.725 | goroutine 368 [running]: |  
  |   | 2023-04-20 12:52:01.725 |   |  

2023-04-20 12:52:01.725panic: series index not found |   |   | 2023-04-20 12:52:01.725 | panic: series index not found
  |   | 2023-04-20 12:52:01.725 | panic: series index not found


```

**Comment by hi-rustin** [comment]
@cyriltovena I guess we can close this issue now.

**Comment by simonswine** [comment]
Yes we can
